# Copied from https://dev.to/willvelida/pushing-container-images-to-github-container-registry-with-github-actions-1m6b

name: Deploy Images to GHCR
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    #defaults:
      #run:
      #  working-directory: ./Store
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'
      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/marcgauch/dashboard-design:latest
          docker push ghcr.io/marcgauch/dashboard-design:latest
